따음표 입력 처리 & 입력단계에서 환경변수 대입
cos18/minishell pull request #23
Opened 2021-01-15 14:36 UTC by cos18

입력 쪼개는 과정을 문자열 더블 포인터에서 libft에서 구현한 연결리스트 기반으로 변경했습니다.

echo와 ~ 대체는 @davkim1030 님이 구현하셨습니다.

Closed #12 #13 #18

2021-01-15 15:02 UTC, davkim1030 requested changes
구현하시느라 수고 많으셨습니다. 그런데 테스트를 해보니 에러 케이스를 몇개 찾아서 코멘트 남깁니다ㅜㅠ. 수정 부탁드립니다!
# 에러 케이스
1. `echo "$PATH"1`와 같이 큰따옴표로 둘러싸인 환경변수 이후에 문자를 붙이면 정상적으로 작동하지 않습니다.
2. `echo '$PWD'`
  - expected: `$PWD`
  - result: `/Users/hyukim/`
3. `echo $12`
  - expected: `2`
  - result: 
4. `echo '$$'`
  - expected: `$$`
  - result: 
5. `echo "\\"`
  - expected: `\`
  - result: `\\`

2021-01-16 06:20 UTC, cos18 commented
> # 에러 케이스
> 1. `echo "$PATH"1`와 같이 큰따옴표로 둘러싸인 환경변수 이후에 문자를 붙이면 정상적으로 작동하지 않습니다.
> 2. `echo '$PWD'`
> 
> * expected: `$PWD`
> * result: `/Users/hyukim/`
> 
> 3. `echo $12`
> 
> * expected: `2`
> * result:
> 
> 4. `echo '$$'`
> 
> * expected: `$$`
> * result:
> 
> 5. `echo "\\"`
> 
> * expected: `\`
> * result: `\\`

확인해본 결과 1, 2, 4는 원래부터 정상적으로 작동되는 것 같고, 3번 항목은 오류가 확인되어 수정했습니다.
5번은 지난번에 말한 역슬래쉬 구현에 관련된 이야기라 따로 구현하지 않아도 괜찮을것 같다는 생각이 드는데, 어떻게 생각하시나요?

2021-01-16 06:32 UTC, davkim1030 requested changes
## 이전 에러
1, 2, 3, 4번 확인해보니 문제 없이 동작합니다!
그런데 5번은 평가표의 아래 부분에 걸릴 것 같다는 생각이 들어서 수정해야되지 않나는 생각이 듭니다.
![image](https://user-images.githubusercontent.com/7599727/104799097-973c5780-580f-11eb-9db3-740f2e919042.png)
## 추가적으로 찾은 에러
1. `echo $`
  - exp: `$`
  - got: segfault
  - `$` 뒤에가 비어있거나 변수 이외의 값이 들어오면 세그폴트가 납니다.
@cos18 수고 많으셨습니다! 하시다가 너무 많거나 힘드시면 월요일로 미루셔도 되고 저한테 맡기셔도 됩니다.

2021-01-16 06:39 UTC, cos18 commented
앗 글쿤요... 일단 역슬래쉬도 구현해 커밋하겠습니다!

2021-01-16 08:32 UTC, cos18 commented
@davkim1030 
역슬래시 관련 작업 추가적으로 진행했고, execve를 통해 외부 명령어를 실행할 때 경로를 입력받았을때 문제가 발생해 이도 수정했습니다. 리뷰 부탁드립니다!

2021-01-16 08:59 UTC, davkim1030 approved these changes
모든 동작이 잘 되는 것을 확인했습니다. 수고 하셨습니다!!

2021-01-16 09:12 UTC, merged