t_bash 구조체 수정으로 인한 리팩터링
cos18/minishell pull request #5
Opened 2021-01-05 06:46 UTC by davkim1030

`t_bash` 구조체 내용 변경

closed #2

2021-01-05 07:01 UTC, cos18 requested changes
해당 내용 포함해 #2 에서 언급한 추가 사항도 수정 부탁드립니다!

2021-01-05 07:01 UTC, cos18 commented on srcs/main.c
> +	cmd_status = get_command();
```suggestion
	cmd_status = get_command();
```

이 함수에서 사용하는 `cmd` 역시 `g_bash->cmd`로 교체 가능한 것 같습니다.

2021-01-05 17:45 UTC, davkim1030 commented on srcs/main.c
> +	cmd_status = get_command();
넵 그러네요. 요청하신 부분 처리했습니다!

2021-01-05 17:48 UTC, davkim1030 reviewed
`cmd` 사용했던 부분을 전부 `g_bash->cmd`로 리팩터링하고 norm, 빌드 이상 없는 것 확인했습니다. 승인 부탁드립니다

2021-01-06 05:41 UTC, cos18 requested changes
`hello"world"world`에 대해 `g_bash->cmd`값이 `helloworldwolrd`가 나옵니다. 확인 부탁드립니다!

2021-01-07 09:31 UTC, davkim1030 commented
`"`, `'`, `\`를 포함한 요청사항 부분 모두 처리하였습니다. 확인 부탁드립니다!

2021-01-07 16:24 UTC, cos18 approved these changes
문제없이 정상 작동되는 것 같습니다. 수고많으셨습니다 👍

2021-01-07 16:24 UTC, merged